SELECT EXTRACT(DAY FROM NOW());
SELECT EXTRACT(YEAR FROM NOW());
-- ...
-- EXTRACT extracts part of a date

SELECT MONTHNAME(NOW()), DAYNAME(NOW());

SELECT YEAR(NOW()), MONTH(NOW()), DAY(NOW()), HOUR(NOW()), MINUTE(NOW()), SECOND(NOW());

SELECT NOW(), CURDATE(), CURTIME();